### PR TITLE
Add Neighbours highlight on mouseover.

### PR DESCRIPTION
**Pull request by greebie**
**The title of this pull-request should be a brief description of what the pull-request fixes/improves/changes. Ideally 50 characters or less.**

- Add arrows to show direction of links.
- Highlights a node's neighbours on hover. (Greys out non-neighbours).

**GitHub issue(s)**:

If you are responding to an issue, please mention their numbers below.

* ex: #130 

# What does this Pull Request do?

Easiest is with screen shots:

image

to:
image

When you mouse over "nanaimodailynews"

# How should this be tested?

- Hover-over should work in regular and full-screen.
- It should also work if you back out of a screen and go to another network.
- Should pass Travis and linting tests.
- Arrow sizing and interaction should work according to UI preferences of the team (ie. I can make things bigger, louder or whatnot as desired).

# Additional Notes:

# Interested parties

@ianmilligan1 @SamFritz 

Thanks in advance for your help with the Archives Unleashed Toolkit!

### CODE REVIEW

**Comment by greebie** [comment]
On larger graphs, I found it hard to see some nodes because they were hidden behind others that were blanked out.  So I added some alpha settings for the nodes.

Also found that refreshing for very large graphs can be pretty annoying, so I set some timeouts so that it does not potato a browser.

**Comment by ianmilligan1** [comment]
On Safari 11.1.1 and Firefox 60.0.2 when I hover over a node, the rest of the network _disappears_ rather than shading like you had above. i.e.

screen shot 2018-06-27 at 9 46 07 pm

I prefer the look of the shading if possible. 

Otherwise, I am enjoying the look and feel of this - on some collections it is really letting me see the network characteristics quite nicely.

**Comment by greebie** [comment]
Okay - we can play with the shadings.  On some of the larger networks it was impossible to see the nodes at all.  Maybe with a hint of color or less transparency.

**Comment by ianmilligan1** [comment]
Maybe this is my colour blindness playing up? The shading you gave in your screenshots seemed pretty good to me, or at least I could see there were nodes without having to put my eyes within a cm of my screen. 😄

**Comment by greebie** [comment]
It's this one that gives trouble.  See:

image

vs

image

**Comment by greebie** [comment]
(Oh and I just darkened the grey in the last case -- no colors that you cannot see!)

**Comment by ianmilligan1** [comment]
I changed line 190 in graph.js to

```
        e.color = 'rgba(238, 238, 238, 1)';
```

And the ensuing graph seems like the right hint - I can see that there are other nodes but they're not obtrusive.

screen shot 2018-06-27 at 10 09 17 pm

There's no way to bring the selected "edge" lines to front though, is there? I can see the problem of your top example in the last comment and in this one that there are the non-selected edges that can obscure the selected edges.

**Comment by greebie** [comment]
Still pretty nasty results with no transparency on a larger graph:

image

I think darker color with a little transparency (eg. try (200, 200, 200, 0.8) is the way forward.  I see no direct way to move the edges up in sigma.  Also, it would require iterating through the edge list which could be prohibitive for larger graphs.

**Comment by greebie** [comment]
Also - it looks like I mucked up the fork again! I'll figure out how to fix all that nonsense tomorrow.  Blech.

**Pull request merged**
