### PR TITLE
Catch if a Spark job really fails; resolve #76.

### LINKED ISSUE #76: Auk sends email on failed job.
I had a job blow up due to memory errors, but an email was still sent telling me that it was analyzed.  May need some conditional wording to check for failed run.

### PR DESCRIPTION
**Pull request by ruebot**
@ianmilligan1 @greebie can y'all test this when you have time?

### CODE REVIEW

**Comment by ianmilligan1** [comment]
Yep will do - probably Tuesday realistically!

**Comment by ianmilligan1** [comment]
Sorry - I won't in the future.

**Comment by greebie** [comment]
Tested with a bad spark-shell path.   No email!

**Comment by ianmilligan1** [comment]
OK thanks @greebie, appreciate the test!

**Pull request merged**
